use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    any_test::run()
}
